version: '3.8'
services:
  db:
    image: ankane/pgvector:latest
    container_name: rag-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rag_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/docker:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
    name: rag-postgres-data
